#!/usr/bin/env bun
import { readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import formatArg from '@/dev-tools/utils/format/formatArg';
import formatCommand from '@/dev-tools/utils/format/formatCommand';

import sysPaths from '../src/config/sysPaths';
import type { CommandEntry } from '../src/types/CommandEntry';
import getCommandEntries from '../src/utils/getCommandEntries';

const outputPath = join(sysPaths.rootDir, '.gitconfig-commands');

const header = [
  '#! Generated by scripts/generate-commands.ts — do not edit by hand.',
  '#! Regenerate with `bun scripts/generate-commands.ts`.',
  '',
  '[alias]',
  '',
].join('\n');

interface GitCommand extends CommandEntry {
  /** Git alias key, which cannot contain a slash. */
  alias: string;
}

const toGitCommand = (entry: CommandEntry): GitCommand => ({
  ...entry,
  //? Nested commands (`subrepo/install`) stay slash-separated for the CLI, which resolves the
  //? name straight onto a path, but git config keys only take `[A-Za-z0-9-]`, so the alias
  //? flattens to `subrepo-install`.
  alias: entry.name.replaceAll('/', '-'),
});

/** Two commands mapping onto one alias would silently drop one of them from the output. */
const assertNoAliasCollisions = (commands: GitCommand[]) => {
  const seen = new Map<string, string>();
  for (const { name, alias } of commands) {
    const previous = seen.get(alias);
    if (previous)
      throw new Error(
        `Commands ${formatArg(previous)} and ${formatArg(name)} both map onto ` +
          `alias ${formatArg(alias)}`,
      );
    seen.set(alias, name);
  }
};

const formatEntry = ({ name, alias, meta }: GitCommand) => {
  //? A description spanning several lines would put raw text on its own uncommented line and
  //? break the config, so collapse whitespace before prefixing the single `#`.
  const description = meta?.description && `# ${meta.description.replace(/\s+/g, ' ').trim()}`;
  return [description, `${alias} = "!git giti ${name}"`].filter(Boolean).join('\n');
};

/** One alias per command group folder so `git branch status` dispatches via `giti branch status`. */
const getFolderAliases = (): GitCommand[] => {
  const { commandsDir } = sysPaths;
  const leafNames = new Set(
    readdirSync(commandsDir)
      .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
      .map((f) => f.slice(0, -'.ts'.length)),
  );

  return readdirSync(commandsDir)
    .filter((entry) => {
      try {
        return statSync(join(commandsDir, entry)).isDirectory();
      } catch {
        return false;
      }
    })
    .filter((dir) => !leafNames.has(dir)) //? skip if a same-named leaf already covers it
    .sort()
    .map((dir) => ({
      name: dir,
      key: dir,
      path: join(commandsDir, dir),
      alias: dir,
      //? No description: folder aliases are navigational, not commands in their own right
    }));
};

const run = async () => {
  const leafCommands = (await getCommandEntries()).map(toGitCommand);
  const folderCommands = getFolderAliases();

  //? Merge and sort so the output file reads alphabetically regardless of which kind each entry is
  const commands = [...leafCommands, ...folderCommands].sort((a, b) =>
    a.alias.localeCompare(b.alias),
  );

  assertNoAliasCollisions(commands);

  await Bun.write(outputPath, `${header}${commands.map(formatEntry).join('\n\n')}\n`);

  const leafCount = formatArg(String(leafCommands.length));
  const folderCount = formatArg(String(folderCommands.length));
  console.log(
    `${formatCommand('giti')} wrote ${leafCount} command aliases + ${folderCount} group aliases to ${formatArg(outputPath)}`,
  );
};

if (import.meta.main) await run();

export default run;
