/**
 * Rule formats: one canonical Markdown file in `.agents`, rendered into what
 * each IDE actually reads.
 *
 * The canonical form is Markdown with optional front matter:
 *
 * ```md
 * ---
 * description: How we write tests
 * globs: ["src/**\/*.test.ts"]   # or `paths:` — Claude Code's own name for it
 * alwaysApply: false
 * ---
 * Body…
 * ```
 *
 * An IDE that reads that as-is (Claude Code's `.claude/rules`, Antigravity's
 * `.agent/rules`) gets a symlink. One that does not gets a generated copy in its
 * own format, marked as generated so it is never mistaken for — or edited as —
 * the source:
 *
 * - Cursor: `.cursor/rules/<name>.mdc`, front matter `description` / `globs`
 *   (comma-separated) / `alwaysApply`
 * - GitHub Copilot: `.github/instructions/<name>.instructions.md`, front matter
 *   `applyTo` (comma-separated globs, `**` for everything)
 * - GitHub Copilot prompts: `.github/prompts/<name>.prompt.md`, front matter
 *   `description`
 */

export type FormatId = 'cursor-mdc' | 'copilot-instructions' | 'copilot-prompt';

export interface CanonicalRule {
  description?: string;
  globs: string[];
  alwaysApply?: boolean;
  /** Everything after the front matter, as written. */
  body: string;
  /** Front matter keys this module does not know, carried through untouched. */
  extra: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Front matter — the subset rule files actually use
// ---------------------------------------------------------------------------

const unquote = (value: string) => value.trim().replace(/^(['"])(.*)\1$/, '$2');

/** `[a, "b"]`, `a, b`, or a single value → a list. */
const toList = (value: string): string[] => {
  const trimmed = value.trim();
  const inner = trimmed.startsWith('[') && trimmed.endsWith(']') ? trimmed.slice(1, -1) : trimmed;
  return inner.split(',').map(unquote).filter(Boolean);
};

/**
 * Split a file into front matter and body.
 *
 * Deliberately not a YAML parser: rule front matter is flat `key: value` lines
 * plus the odd `- item` list, and pulling a YAML dependency into a CLI for
 * that is more surface than it is worth. Anything nested is kept as its raw
 * text under its key, so it survives a round trip even if nothing here reads it.
 */
export const parseFrontMatter = (
  text: string,
): { data: Record<string, string | string[]>; body: string } => {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) return { data: {}, body: text };
  const data: Record<string, string | string[]> = {};
  let listKey: string | undefined;
  for (const line of (match[1] ?? '').split(/\r?\n/)) {
    const item = line.match(/^\s+-\s+(.*)$/);
    if (item && listKey) {
      const current = data[listKey];
      data[listKey] = [...(Array.isArray(current) ? current : []), unquote(item[1] ?? '')];
      continue;
    }
    const pair = line.match(/^([A-Za-z_][\w-]*)\s*:\s*(.*)$/);
    if (!pair?.[1]) continue;
    listKey = pair[2]?.trim() === '' ? pair[1] : undefined;
    data[pair[1]] = pair[2]?.trim() === '' ? [] : unquote(pair[2] ?? '');
  }
  return { data, body: text.slice(match[0].length) };
};

const asList = (value: string | string[] | undefined): string[] =>
  value === undefined ? [] : Array.isArray(value) ? value : toList(value);

const asBool = (value: string | string[] | undefined): boolean | undefined =>
  value === 'true' ? true : value === 'false' ? false : undefined;

const KNOWN = new Set(['description', 'globs', 'paths', 'alwaysApply', 'applyTo']);

export const parseCanonical = (text: string): CanonicalRule => {
  const { data, body } = parseFrontMatter(text);
  const extra: Record<string, string> = {};
  for (const [key, value] of Object.entries(data)) {
    if (!KNOWN.has(key)) extra[key] = Array.isArray(value) ? JSON.stringify(value) : value;
  }
  return {
    description: typeof data.description === 'string' ? data.description : undefined,
    //? `paths` is Claude Code's name, `globs` Cursor's, `applyTo` Copilot's —
    //? any of them in the source means the same thing
    globs: [...asList(data.globs), ...asList(data.paths), ...asList(data.applyTo)].filter(
      (glob) => glob !== '**',
    ),
    alwaysApply: asBool(data.alwaysApply),
    body: stripMarker(body),
    extra,
  };
};

// ---------------------------------------------------------------------------
// The generated-file marker
// ---------------------------------------------------------------------------

const MARKER_PREFIX = '<!-- generated by agenti from ';

/** The line every generated file carries right after its front matter. */
export const generatedMarker = (sourceRel: string) =>
  `${MARKER_PREFIX}${sourceRel} — edit that file, not this one -->`;

export const isGenerated = (text: string) => text.includes(MARKER_PREFIX);

const stripMarker = (body: string) =>
  body
    .split('\n')
    .filter((line) => !line.startsWith(MARKER_PREFIX))
    .join('\n')
    .replace(/^\n+/, '');

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const yamlString = (value: string) =>
  /[:#"'\n]|^\s|\s$/.test(value) ? JSON.stringify(value) : value;

const frontMatter = (entries: [string, string | undefined][]) => {
  const lines = entries.filter(([, value]) => value !== undefined).map(([k, v]) => `${k}: ${v}`);
  return lines.length ? `---\n${lines.join('\n')}\n---\n` : '';
};

/** A source file's name as the IDE expects it: `testing.md` → `testing.mdc`. */
export const targetName = (format: FormatId | undefined, name: string): string => {
  if (!format || !name.endsWith('.md')) return name;
  const stem = name.slice(0, -3);
  if (format === 'cursor-mdc') return `${stem}.mdc`;
  if (format === 'copilot-instructions') return `${stem}.instructions.md`;
  return `${stem}.prompt.md`;
};

/** The inverse of `targetName`, for adopting an IDE-only file into `.agents`. */
export const sourceName = (format: FormatId | undefined, name: string): string | undefined => {
  if (!format) return name;
  const suffix =
    format === 'cursor-mdc'
      ? '.mdc'
      : format === 'copilot-instructions'
        ? '.instructions.md'
        : '.prompt.md';
  return name.endsWith(suffix) ? `${name.slice(0, -suffix.length)}.md` : undefined;
};

/** The file an IDE reads, generated from a canonical rule. */
export const render = (format: FormatId, source: string, sourceRel: string): string => {
  const rule = parseCanonical(source);
  const marker = `${generatedMarker(sourceRel)}\n\n`;
  const description = rule.description ? yamlString(rule.description) : undefined;

  if (format === 'cursor-mdc') {
    return `${frontMatter([
      ['description', description],
      ['globs', rule.globs.length ? rule.globs.join(',') : undefined],
      //? A rule with no globs and no say either way is one meant to apply
      //? everywhere, which in Cursor has to be spelled out
      ['alwaysApply', String(rule.alwaysApply ?? rule.globs.length === 0)],
    ])}${marker}${rule.body}`;
  }
  if (format === 'copilot-instructions') {
    return `${frontMatter([
      ['applyTo', JSON.stringify(rule.globs.length ? rule.globs.join(',') : '**')],
      ['description', description],
    ])}${marker}${rule.body}`;
  }
  return `${frontMatter([['description', description]])}${marker}${rule.body}`;
};

/**
 * The canonical rule an IDE's file stands for — for adopting a file the IDE
 * has and `.agents` does not. Globs come back under `globs`, the most widely
 * understood name; unknown keys are kept.
 */
export const toCanonical = (targetText: string): string => {
  const rule = parseCanonical(targetText);
  const entries: [string, string | undefined][] = [
    ['description', rule.description ? yamlString(rule.description) : undefined],
    ['globs', rule.globs.length ? JSON.stringify(rule.globs) : undefined],
    ['alwaysApply', rule.alwaysApply === undefined ? undefined : String(rule.alwaysApply)],
    ...Object.entries(rule.extra),
  ];
  return `${frontMatter(entries)}${rule.body}`;
};
